// Generated by gencpp from file cp1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CP1_MESSAGE_ADDTWOINTS_H
#define CP1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <cp1/AddTwoIntsRequest.h>
#include <cp1/AddTwoIntsResponse.h>


namespace cp1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace cp1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cp1::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::cp1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::cp1::AddTwoInts > {
  static const char* value()
  {
    return "cp1/AddTwoInts";
  }

  static const char* value(const ::cp1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::cp1::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::cp1::AddTwoInts >
template<>
struct MD5Sum< ::cp1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cp1::AddTwoInts >::value();
  }
  static const char* value(const ::cp1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cp1::AddTwoIntsRequest> should match
// service_traits::DataType< ::cp1::AddTwoInts >
template<>
struct DataType< ::cp1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cp1::AddTwoInts >::value();
  }
  static const char* value(const ::cp1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cp1::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::cp1::AddTwoInts >
template<>
struct MD5Sum< ::cp1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cp1::AddTwoInts >::value();
  }
  static const char* value(const ::cp1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cp1::AddTwoIntsResponse> should match
// service_traits::DataType< ::cp1::AddTwoInts >
template<>
struct DataType< ::cp1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cp1::AddTwoInts >::value();
  }
  static const char* value(const ::cp1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CP1_MESSAGE_ADDTWOINTS_H
