// Generated by gencpp from file cp3/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CP3_MESSAGE_ADDTWOINTS_H
#define CP3_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <cp3/AddTwoIntsRequest.h>
#include <cp3/AddTwoIntsResponse.h>


namespace cp3
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace cp3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cp3::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::cp3::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::cp3::AddTwoInts > {
  static const char* value()
  {
    return "cp3/AddTwoInts";
  }

  static const char* value(const ::cp3::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::cp3::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::cp3::AddTwoInts >
template<>
struct MD5Sum< ::cp3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cp3::AddTwoInts >::value();
  }
  static const char* value(const ::cp3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cp3::AddTwoIntsRequest> should match
// service_traits::DataType< ::cp3::AddTwoInts >
template<>
struct DataType< ::cp3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cp3::AddTwoInts >::value();
  }
  static const char* value(const ::cp3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cp3::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::cp3::AddTwoInts >
template<>
struct MD5Sum< ::cp3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cp3::AddTwoInts >::value();
  }
  static const char* value(const ::cp3::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cp3::AddTwoIntsResponse> should match
// service_traits::DataType< ::cp3::AddTwoInts >
template<>
struct DataType< ::cp3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cp3::AddTwoInts >::value();
  }
  static const char* value(const ::cp3::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CP3_MESSAGE_ADDTWOINTS_H
