// Generated by gencpp from file contest/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CONTEST_MESSAGE_ADDTWOINTS_H
#define CONTEST_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <contest/AddTwoIntsRequest.h>
#include <contest/AddTwoIntsResponse.h>


namespace contest
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace contest


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::contest::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::contest::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::contest::AddTwoInts > {
  static const char* value()
  {
    return "contest/AddTwoInts";
  }

  static const char* value(const ::contest::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::contest::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::contest::AddTwoInts >
template<>
struct MD5Sum< ::contest::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::contest::AddTwoInts >::value();
  }
  static const char* value(const ::contest::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::contest::AddTwoIntsRequest> should match
// service_traits::DataType< ::contest::AddTwoInts >
template<>
struct DataType< ::contest::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::contest::AddTwoInts >::value();
  }
  static const char* value(const ::contest::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::contest::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::contest::AddTwoInts >
template<>
struct MD5Sum< ::contest::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::contest::AddTwoInts >::value();
  }
  static const char* value(const ::contest::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::contest::AddTwoIntsResponse> should match
// service_traits::DataType< ::contest::AddTwoInts >
template<>
struct DataType< ::contest::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::contest::AddTwoInts >::value();
  }
  static const char* value(const ::contest::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTEST_MESSAGE_ADDTWOINTS_H
