// Generated by gencpp from file cp4/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CP4_MESSAGE_ADDTWOINTS_H
#define CP4_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <cp4/AddTwoIntsRequest.h>
#include <cp4/AddTwoIntsResponse.h>


namespace cp4
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace cp4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cp4::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::cp4::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::cp4::AddTwoInts > {
  static const char* value()
  {
    return "cp4/AddTwoInts";
  }

  static const char* value(const ::cp4::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::cp4::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::cp4::AddTwoInts >
template<>
struct MD5Sum< ::cp4::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cp4::AddTwoInts >::value();
  }
  static const char* value(const ::cp4::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cp4::AddTwoIntsRequest> should match
// service_traits::DataType< ::cp4::AddTwoInts >
template<>
struct DataType< ::cp4::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cp4::AddTwoInts >::value();
  }
  static const char* value(const ::cp4::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cp4::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::cp4::AddTwoInts >
template<>
struct MD5Sum< ::cp4::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cp4::AddTwoInts >::value();
  }
  static const char* value(const ::cp4::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cp4::AddTwoIntsResponse> should match
// service_traits::DataType< ::cp4::AddTwoInts >
template<>
struct DataType< ::cp4::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cp4::AddTwoInts >::value();
  }
  static const char* value(const ::cp4::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CP4_MESSAGE_ADDTWOINTS_H
